[package]
name = "bevy_craft"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.2", features = ["wayland"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
